version: '3.9'

services:
  node-webapp:
    container_name: node-webapp
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=5173
      - HOST=0.0.0.0
      - VIRTUAL_HOST=react.arpa
      - VIRTUAL_PORT=5173
    ports:
      - '5173:5173'

  node-express:
    container_name: node-express
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=5000
      - HOST=0.0.0.0
      - VIRTUAL_HOST=api.arpa
      - VIRTUAL_PORT=5000
    ports:
      - '5000:5000'
