version: '3.9'

services:
  node-web-app:
    container_name: node-web-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=5173
      - HOST=0.0.0.0
      - VIRTUAL_HOST=react.arpa
      - VIRTUAL_PORT=5173
    ports:
      - '5173:5173'
